-- MySQL Script generated by MySQL Workbench
-- Thu Feb 12 15:29:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wbc22
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wbc22` ;

-- -----------------------------------------------------
-- Schema wbc22
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wbc22` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `wbc22` ;

-- -----------------------------------------------------
-- Table `wbc22`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wbc22`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wbc22`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` CHAR(9) NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wbc22`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wbc22`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wbc22`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` CHAR(9) NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wbc22`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wbc22`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wbc22`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_customer_idx` (`cus_id` ASC) VISIBLE,
  INDEX `fk_pet_petstore1_idx` (`pst_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_customer`
    FOREIGN KEY (`cus_id`)
    REFERENCES `wbc22`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_petstore1`
    FOREIGN KEY (`pst_id`)
    REFERENCES `wbc22`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wbc22`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `wbc22`;
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Claws and Paws', '123 Main St.', 'Los Angeles', 'CA', '900195341', 8185551234, 'clawsandpaws@aol.com', 'http://www.clawsandpaws.com', 50000.00, 'notes1');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furry Friends', '1435 Chase Dr.', 'Chicago', 'IL', '618959031', 8471234567, 'furryfriends@hotmail.com', 'http://www.furryfriends.com', 65000.00, 'notes2');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Partners', '811 4th St.', 'New York', 'NY', '001256728', 2129876543, 'petpartners@yahoo.com', 'http://www.petpartners.com', 87000.00, 'notes3');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Palace', '18903 Tennessee St.', 'Tallahassee', 'FL', '000036790', 8504445123, 'petpalace@gmail.com', 'http://www.petpalace.com', 34000.00, 'notes4');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Purrs and Grrs', '751 Lois Lane', 'Phoenix', 'AZ', '852122156', 4809130015, 'purrsandgrrs@msn.com', 'http://www.purrsandgrrs.com', 97500.00, 'notes5');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Happy Tails', '400 Oak St.', 'Orlando', 'FL', '328011234', 4075558833, 'happytails@gmail.com', 'http://www.happytails.com', 42000.00, 'notes6');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet World', '99 Main St.', 'Tampa', 'FL', '336021111', 8135552244, 'petworld@gmail.com', 'http://www.petworld.com', 61000.00, 'notes7');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furry House', '22 Pine Rd.', 'Miami', 'FL', '331019999', 3055556677, 'furryhouse@yahoo.com', 'http://www.furryhouse.com', 78000.00, 'notes8');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Critter Corner', '8 Hill St.', 'Atlanta', 'GA', '303031234', 4045551010, 'critter@msn.com', 'http://www.crittercorner.com', 52000.00, 'notes9');
INSERT INTO `wbc22`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Paw Central', '701 Lake Dr.', 'Dallas', 'TX', '752011111', 9725559191, 'pawcentral@gmail.com', 'http://www.pawcentral.com', 69000.00, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `wbc22`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `wbc22`;
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'John', 'Smith', '120 Oak St.', 'Tallahassee', 'FL', '323011234', 8505551122, 'johnsmith@gmail.com', 125.50, 340.00, 'notes1');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Emily', 'Johnson', '44 Pine Rd.', 'Orlando', 'FL', '328021111', 4075553344, 'emilyj@yahoo.com', 0.00, 890.00, 'notes2');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Michael', 'Brown', '991 Lake Dr.', 'Tampa', 'FL', '336031234', 8135557788, 'mbrown@msn.com', 220.75, 1200.00, 'notes3');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Sarah', 'Davis', '18 Hill St.', 'Jacksonville', 'FL', '322011111', 9045558899, 'sarahd@gmail.com', 45.00, 560.25, 'notes4');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Daniel', 'Wilson', '730 Sunset Blvd', 'Los Angeles', 'CA', '900281234', 3105556622, 'dwilson@aol.com', 0.00, 1500.00, 'notes5');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Amanda', 'Martinez', '54 Ocean Ave', 'Miami', 'FL', '331021234', 3055559911, 'amartinez@gmail.com', 80.25, 720.75, 'notes6');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Kevin', 'Thompson', '901 Forest Ln', 'Atlanta', 'GA', '303031111', 4045557766, 'kthompson@yahoo.com', 300.00, 980.50, 'notes7');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Laura', 'Nguyen', '66 Maple St', 'Dallas', 'TX', '752011234', 9725552244, 'lnguyen@gmail.com', 0.00, 430.00, 'notes8');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Brian', 'Miller', '215 River Rd', 'Phoenix', 'AZ', '850011111', 6025553300, 'bmiller@msn.com', 60.00, 610.25, 'notes9');
INSERT INTO `wbc22`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Natalie', 'Carter', '11 Cedar Ct', 'Denver', 'CO', '802021234', 7205554488, 'ncarter@gmail.com', 150.00, 845.00, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `wbc22`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `wbc22`;
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 1, 'Dog', 'm', 300.00, 650.00, 2, 'Brown', '2025-01-10', 'y', 'y', 'notes1');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 2, 'Cat', 'f', 150.00, 400.00, 1, 'Gray', '2025-01-12', 'y', 'n', 'notes2');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 3, 'Rabbit', 'm', 80.00, 200.00, 1, 'White', '2025-01-15', 'n', 'n', 'notes3');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 4, 'Dog', 'f', 350.00, 700.00, 3, 'Black', '2025-01-18', 'y', 'y', 'notes4');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 5, 'Parrot', 'm', 200.00, 500.00, 4, 'Green', '2025-01-20', 'n', 'n', 'notes5');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 6, 'Dog', 'm', 250.00, 600.00, 2, 'Golden', '2025-01-22', 'y', 'y', 'notes6');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, NULL, 'Hamster', 'f', 20.00, 60.00, 1, 'Tan', NULL, 'n', 'n', 'notes7');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, NULL, 'Cat', 'f', 120.00, 350.00, 2, 'White', NULL, 'y', 'n', 'notes8');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, NULL, 'Snake', 'm', 90.00, 250.00, 3, 'Green', NULL, 'n', 'n', 'notes9');
INSERT INTO `wbc22`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, NULL, 'Turtle', 'm', 60.00, 180.00, 5, 'Green', NULL, 'n', 'n', 'notes10');

COMMIT;

